### ISSUE TITLE
老铁，MIT6.375 Lab5 能过吗

### ISSUE THREAD

**Issue by GTwhy** [adamgallas/MIT_Bluespec_RISCV_Tutorial#1]
老铁，375的lab5/bolib/*.bo我看是用vsc-2017.A商业版编译的，我用最新的开源版bsc编译lab5的时候会报错 version mismatch，貌似要用统一版本的bsc编译包括bolib/下的依赖和其他源文件，但bolib它没提供源码呀，你有什么办法编译通过吗，求教一下。

**Comment by adamgallas** [comment]
哎，我也编译不过，我也解决不了这个问题。。。
所以最后我是没有用lab5-harness的文件，就把175的include搬过来，按照自己的理解完成它的exercise的

**Comment by GTwhy** [comment]
哈哈好主意，强啊！我是做175的lab5用最新的工具链发现要改不少东西，新工具链里没elf2hex，找的sifive的elf2hex工具编出来的vmh是运行起来是死循环，感觉不太对劲，然后想看看375 lab5，结果发现问题更多。。。

话说我看你在175用了[riscv-special](https://github.com/adamgallas/MIT_Bluespec_RISCV_Tutorial/blob/main/mit_6.175_riscv_lab/mit_6.175_riscv_1/programs/assembly/Makefile#L42)的elf2bin，这是哪里下载的工具链呀，功能正常么

**Comment by adamgallas** [comment]
我是clone了这个repo[riscv-fesvr](https://github.com/riscvarchive/riscv-fesvr)，./configure一下直接make，build出了elf2hex，我好像是从哪google到这个方法的。不过我刚刚搜了搜，elf2hex应该在riscv-tools里面也有，你看看riscv-tools能不能安装成功？或许看看这个[教程](https://riscv.org/wp-content/uploads/2015/01/riscv-software-stack-bootcamp-jan2015.pdf)

**Comment by GTwhy** [comment]
顺着你给的riscv-fesvr找到了[riscv-isa-sim](https://github.com/riscv-software-src/riscv-isa-sim)，编译完就有elf2hex了，这个应该比较新，也能顺利编译出vmh。不过第一次跑的时候发现正常运行了一段时间之后还是死循环了，原因是csr mtohost新版spec和gcc都不支持了，我换成了mcontext，但没替换全，有的地址还是原来mtohost的，按照新的spec改完之后跑通了。非常感谢！！

**Comment by adamgallas** [comment]
跑通了就好。确实我当时做的时候各种环境也很头疼。不过后面可能就比较顺利了。不过175的exception的实验可能还会遇到一些问题，但具体也忘了。有问题再来问我吧！

**Comment by GTwhy** [comment]
好嘞，Thanks♪(･ω･)ﾉ
